### PR TITLE
fixes #34 (turret PIDs)

### LINKED ISSUE #34: Turret PIDs
- turn to target pid needs to be both started and finsihed
- also needs tyo be tuned
- turret to angle pid to be created

### PR DESCRIPTION
**Pull request by hmagan**
did it but I had some questions/concerns so the code needs to be reviewed and likely changed a bit
see issue #34 for details

### CODE REVIEW

**Review by Yukigamine — CHANGES_REQUESTED** [review]
We should set up constants this subsystem's PID values so we don't have to tweak them in two different commands. Eg. `kPTurretVel` or something.

In `TurnToAnglePIDCommand`, just one comment:
We need to figure out whether we are working with relative or absolute positioning.
So are we saying, turn the turret to +5 degrees, or move the turret to +/- 5 degrees from current?
Then we need to make the command either check that the given angle is valid, or allow it to finish if we bump a limit switch. Otherwise we might reach the  limits of the turret and never exit the command.

With `TurnToTargetPIDCommand`:

Output is the raw value of output that the PID loop sends to the motor, not an angle. 
If you want to use the limelight to calculate an angle that the turret needs to turn, you could do that and send the command to the `TurnToAnglePIDCommand` and not have to make this command a PID command. Or, you can use this PID command in the same way you did `TurnToAnglePIDCommand` by doing substituting the `getTX > 0` into the output's if statement.

In this command, we also need to account for the possibility of the command being run while the target is not within view of the LimeLight. If the LimeLight responds 0 when not in view, then it works already, but otherwise we need to figure that out.

Also the same thing needs to be prepared in this command to allow it to exit if we're at limits. Maybe also blink the LEDs red if it can't turn to the requested angle?

**Comment by hmagan** [comment]
I can work on these changes after school, I'll see if I can get it done before 5:00pm.

I can for sure set up some constants quickly.

For `TurnToAnglePIDCommand`, the way it's set up should be relative positioning (which makes more sense imo). We reset the encoders in the `initialize` method so that any turning will be as if the current angle is zero, therefore adding/substracting with respect to the current angle.

As for the other changes, how do we know if an angle is valid? Is it invalid if `angle > 360 || angle < -360`? If so, will something like this work in the `isFinished` method:
```java
public boolean isFinished() {
    return getController().atSetpoint() || turretSubsystem.getPhysicalLimit() || (angle > 360 || angle < -360);
}
```
I would have to declare an `angle` instance variable and initialize in the constructor but that's easy.

For the `TurnToTargetPIDCommand`, I figured that wasn't right, but I should be able to get those changes in. When I check to see if the Limelight doesn't detect the target, could I implement that in a similar way as above? Like so:
```java
public boolean isFinished() {
  return getController().atSetpoint() || Limelight.getTx() == 0;
}
```
As for blinking the LEDs, we could probably do that pretty easily, we just gotta wait for whoever is doing the LED subsystem/commands to finish.

Again, I'll try to get this in after school & before 5:00. I don't think I'm going in the zone today so I could prob just hop on vc and do it (and anything else we still need) then.

**Comment by hmagan** [comment]
Actually, since the setpoint in `TurnToTargetPIDCommand` is 0.0, won't it already stop when `getTx` returns 0? I'm not entirely sure how the LimeLight responds to `getTx` when the target is out of view, but if it just returns 0 shouldn't it be fine?

**Comment by Yukigamine** [comment]
> Again, I'll try to get this in after school & before 5:00. I don't think I'm going in the zone today so I could prob just hop on vc and do it (and anything else we still need) then.

Thanks, I appreciate it!

> For `TurnToAnglePIDCommand`, the way it's set up should be relative positioning (which makes more sense imo). We reset the encoders in the `initialize` method so that any turning will be as if the current angle is zero, therefore adding/substracting with respect to the current angle.

I didn't realize this... We should NEVER reset the encoder for the turret or hood except at the beginning of the match or if we bump the reverse limit switch. Otherwise soft limits won't work and we can easily accidentally turn the turret too far.

> As for the other changes, how do we know if an angle is valid? Is it invalid if `angle > 360 || angle < -360`? If so, will something like this work in the `isFinished` method:

This is close, but it'll probably be something like `angle < 0 || angle > 270` because the movable angle starts at the reverse limit switch and ends at the forward one.

> ```java
> public boolean isFinished() {
>   return getController().atSetpoint() || Limelight.getTx() == 0;
> }
> ```

This should be good, but let's do `return getController().atSetpoint() || Math.abs(Limelight.getTX()) <= 1` to try and get it within 1 degree either direction.

**Comment by hmagan** [comment]
> I didn't realize this... We should NEVER reset the encoder for the turret or hood except at the beginning of the match or if we bump the reverse limit switch. Otherwise soft limits won't work and we can easily accidentally turn the turret too far.

Gotcha. I assume we just use absolute positioning in this case? `angle < 0 || angle > 270` sounds like absolute positioning too but correct me if I'm wrong.

Also, I'm kinda smooth brain and only just realized that in the original change request you were saying that if `getTx` returns 0 when the target isn't located then we don't have to change anything, otherwise we will have to change up the command a bit so sorry bout that.

> This should be good, but let's do return getController().atSetpoint() || Math.abs(Limelight.getTX()) <= 1 to try and get it within 1 degree either direction.

Isn't this what `setTolerance` is for? It's currently set to 1.0 in the constructor.

**Comment by Yukigamine** [comment]
> Gotcha. I assume we just use absolute positioning in this case? `angle < 0 || angle > 270` sounds like absolute positioning too but correct me if I'm wrong.

Yeah, that's absolute positioning. But if you wanted to set up your command to take a relative angle, you could calculate the absolute position with a quick line like `setPoint = currentPos + angle` and then check the set point against valid angles.


> Also, I'm kinda smooth brain and only just realized that in the original change request you were saying that if `getTx` returns 0 when the target isn't located then we don't have to change anything, otherwise we will have to change up the command a bit so sorry bout that.

That's all good, it's a behavior we probably need to check when we're in the zone unless LimeLight's docs have information about it.
 
> Isn't this what `setTolerance` is for? It's currently set to 1.0 in the constructor.

Yes true, but you have only done `setTolerance` on the `TurnToAnglePIDCommand` and not `TurnToTargetPIDCommand`. So if you add a tolerance, then you can probably just ditch `|| LimeLight.getTX() == 0` altogether.

**Comment by hmagan** [comment]
Got it. Also, it's already there on line 34—you might have overlooked it.

https://github.com/Yeti-Robotics/olaf-java-2021/blob/d3e0a2895832306f4f479d5f6d5c4566841abbe4/src/main/java/frc/robot/commands/turret/TurnToTargetPIDCommand.java#L34

**Comment by Yukigamine** [comment]
> 
> 
> Got it. Also, it's already there on line 34—you might have overlooked it.
> 
> https://github.com/Yeti-Robotics/olaf-java-2021/blob/d3e0a2895832306f4f479d5f6d5c4566841abbe4/src/main/java/frc/robot/commands/turret/TurnToTargetPIDCommand.java#L34


I definitely did overlook it! Turns out GitHub was hiding that one line when I was looking at the file through the PR changes. 😂

**Comment by Yukigamine** [comment]
That latest commit looks really good! One final suggestion: use a constant called `TURRET_MAX_ANGLE` or something in place of `270` in that or statement.

**Review by Yukigamine — APPROVED** [review]

**Pull request merged**
